#!/usr/bin/env sh
# Persist the Exp-1 P0 chamber run's event log to a file: re-loadable, sorted
# (event Seq Rule Key) facts. PeTTa has no MeTTa-level file write, so this runs
# petta/dump_log.metta, strips the runner's transpilation trace + ANSI colour, and
# redirects the clean facts to the output file (with a header comment).
#
# Usage:  sh petta/dump_log.sh [output_path]      (default: runs/LOG_e1.metta)
SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
REPO=$(dirname "$SCRIPT_DIR")
RUNNER="$REPO/../PeTTa/run.sh"
cd "$REPO" || exit 2
OUT=${1:-runs/LOG_e1.metta}
mkdir -p "$(dirname "$OUT")"
{
  echo "; Event log — persisted run of the Exp-1 P0 chamber. Bare (event Seq Rule Key)"
  echo "; facts, sorted by firing sequence; re-loadable (import!) and diff-able."
  echo "; Generated by: sh petta/dump_log.sh"
  sh "$RUNNER" petta/dump_log.metta < /dev/null 2>&1 \
    | sed 's/\x1b\[[0-9;]*m//g' \
    | grep '^(event '
} > "$OUT"
n=$(grep -c '^(event ' "$OUT")
echo "wrote $n events to $OUT"
